sudo: false
language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "lts/argon"
  - "lts/boron"
  - "node"
  - "iojs"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
